### ISSUE TITLE
...

### ISSUE THREAD

**Issue by handicraftsman** [handicraftsman/baseOS#2]
Боже мой! Что же ты натворил с осью, изя? И апдейт панелей кривой, и нижняя панель пропадает после запуска другого софта!

**Comment by vaartis** [comment]
Так и было ( ͡° ͜ʖ ͡°)

**Comment by handicraftsman** [comment]
Ладно. Сделаю потом переменные minY и maxY для багофикса. И топик разлочили.

**Comment by handicraftsman** [comment]
@TyanNN, обновил топик. Добавил ссылки на вики и issuetracker. Щас ещё на ustable ветку добавлю (master)
